### ISSUE TITLE
program() incorrectly thinks shaders are urls...

### ISSUE THREAD

**Issue by bman654** [skeeto/igloojs#2]
If I have my shaders as JavaScript strings like so:

``` javascript
var vert = "attribute vec2 a_position;\n\nvoid main() {\n    gl_Position = vec4(a_position, 0, 1);\n}\n\n";
var frag = "void main() {\n    gl_FragColor = vec4(0, 1, 0, 1); // green\n}\n";
```

and then try to create my program:

``` javascript
var program = igloo.program(vert, frag);
```

program thinks my shaders are urls and tries to download them.

The work-around seems to be to put a space at the start of my strings:

``` javascript
var program = igloo.program(" " + vert, " " + frag);
```

It seems like this Regex should be changed:

``` javascript
Igloo.looksLikeURL = function(string) {
    //return /^[\w+:\/\/]/.exec(string) != null;
    return /^\w+:\/\//.exec(string) != null;
};
```

**Comment by skeeto** [comment]
Thanks, I have no idea why I put those brackets in the regex! Must have
been some sort of typo.

**Comment by bman654** [comment]
Thanks, though now that you've done it, I think it breaks your demo, which relies on relative urls.

I wonder if you should change it to something like `/void\s+main\s*(\s*)/.test(string) === null` since it is sort of hard to accurately detect things that look like urls, but all shader programs will have `void main()` in them...

**Comment by skeeto** [comment]
Ha, that's what I get for not testing first. The fact that it worked in
the first place was just luck. Rather than look for "void main," I
changed it so that any whitespace means it's a shader. URLs will have
their whitespace encoded (i.e. %20) and won't have whitespace.

**Comment by bman654** [comment]
:+1:
