### ISSUE TITLE
gl.getError() in Igloo.Program.prototype.draw causes huge performance loss in Chrome

### ISSUE THREAD

**Issue by saliksyed** [skeeto/igloojs#7]
The draw call checks for errors everytime it is called on line 299. This is okay if you are just rendering a single quad but if using Igloo to render lots of quads this causes a huge performance hit, in fact it sometimes takes 2-3 ms per quad. Commenting out the line sped up performance a lot so maybe it is worth making it optional.

Chrome Version 62.0.3202.94 (Official Build) (64-bit) on Mac OS X  El Capitan (2015 Macbook Pro 15" AMD Radeon R9 M370X 2048 MB)

<img width="580" alt="perf" src="https://user-images.githubusercontent.com/631426/33555418-5592b982-d8ce-11e7-8c0c-4028b3f6f0c4.png">

**Comment by skeeto** [comment]
Great observation! My guess is it's flushing the pipeline — essentially 
waiting for the draw to fully complete. While this is so useful for 
debugging, I'm thinking the error check should be disabled by default.

Thanks!
